List filterTypes = [
  {'id': 1, 'name': 'All'},
  {'id': 2, 'name': 'Онцлох'},
  {'id': 3, 'name': 'Хямдралтай'},
  {'id': 4, 'name': 'Шинэ бараа'}
];

List categories = [
  {
    'id': 1,
    'name': "Clothes",
    'image': "assets/icons/categories/clothes.svg",
  },
  {
    'id': 2,
    'name': "For Kids",
    'image': "assets/icons/categories/kids.svg",
  },
  {
    'id': 3,
    'name': "Chair",
    'image': "assets/icons/categories/chair.svg",
  },
  {
    'id': 4,
    'name': "Beauty",
    'image': "assets/icons/categories/beauty.svg",
  },
  {
    'id': 5,
    'name': "Sports",
    'image': "assets/icons/categories/sport.svg",
  },
  {
    'id': 6,
    'name': "Clothes",
    'image': "assets/icons/categories/clothes.svg",
  },
  {
    'id': 7,
    'name': "For Kids",
    'image': "assets/icons/categories/kids.svg",
  }
];

List sellers = [
  {
    'id': 1,
    'name': 'Уянга Төр',
    'phone': 88903949,
    'email': 'uyanga.kh@gmail.com',
    'description':
        "We’ve got options to get you where you’re going. Choose a ride* that suits your mood and budget.",
    'image': 'assets/img/avatar.png',
  },
  {
    'id': 2,
    'name': 'Уянга Төр',
    'phone': 88903949,
    'email': 'uyanga.kh@gmail.com',
    'description':
        "We’ve got options to get you where you’re going. Choose a ride* that suits your mood and budget.",
    'image': 'assets/img/avatar.png',
  }
];

List products = [
  {
    'id': 1,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_1.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Онцлох',
    'status': 'Тийм',
    'count': '350',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': '42 67 98',
    'color': 'хар цагаан бор',
    'shop_id': 1,
  },
  {
    'id': 2,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_2.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Онцлох',
    'status': 'Тийм',
    'count': '250',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': null,
    'color': null,
    'shop_id': 1,
  },
  {
    'id': 3,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_3.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Онцлох',
    'status': 'Тийм',
    'count': '650',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': '42 67 98',
    'color': 'хар цагаан бор',
    'shop_id': 1,
  },
  {
    'id': 4,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_4.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Хямдралтай',
    'status': 'Тийм',
    'count': '450',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': null,
    'color': null,
    'shop_id': 1,
  },
  {
    'id': 5,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_5.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Хямдралтай',
    'status': 'Тийм',
    'count': '350',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': '42 67 98',
    'color': 'хар цагаан бор',
    'shop_id': 2,
  },
  {
    'id': 6,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_6.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Шинэ бараа',
    'status': 'Тийм',
    'count': '350',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': null,
    'color': null,
    'shop_id': 2,
  },
  {
    'id': 7,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_7.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Шинэ бараа',
    'status': 'Тийм',
    'count': '350',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': '42 67 98',
    'color': 'хар цагаан бор',
    'shop_id': 2,
  },
  {
    'id': 8,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_8.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Шинэ бараа',
    'status': 'Тийм',
    'count': '350',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': null,
    'color': null,
    'shop_id': 2,
  },
];

List notificationList = [
  {
    'id': 1,
    'title': 'Notification',
    'description':
        'Most of the people you’ll meet will mostly already a part of a friend group.',
    'status': true,
  },
  {
    'id': 2,
    'title': 'Notification',
    'description':
        'Most of the people you’ll meet will mostly already a part of a friend group.',
    'status': true,
  },
  {
    'id': 3,
    'title': 'Notification',
    'description':
        'Most of the people you’ll meet will mostly already a part of a friend group.',
    'status': true,
  },
  {
    'id': 4,
    'title': 'Notification',
    'description':
        'Most of the people you’ll meet will mostly already a part of a friend group.',
    'status': true,
  },
  {
    'id': 5,
    'title': 'Notification',
    'description':
        'Most of the people you’ll meet will mostly already a part of a friend group.',
    'status': true,
  },
  {
    'id': 6,
    'title': 'Notification',
    'description':
        'Most of the people you’ll meet will mostly already a part of a friend group.',
    'status': true,
  },
  {
    'id': 7,
    'title': 'Notification',
    'description':
        'Most of the people you’ll meet will mostly already a part of a friend group.',
    'status': true,
  },
  {
    'id': 8,
    'title': 'Notification',
    'description':
        'Most of the people you’ll meet will mostly already a part of a friend group.',
    'status': true,
  },
  {
    'id': 9,
    'title': 'Notification',
    'description':
        'Most of the people you’ll meet will mostly already a part of a friend group.',
    'status': true,
  },
  {
    'id': 10,
    'title': 'Notification',
    'description':
        'Most of the people you’ll meet will mostly already a part of a friend group.',
    'status': true,
  },
];

List shopList = [
  {
    'id': 1,
    'name': 'Тест Дэлгүүр',
    'description': 'Тухайн дэлгүүрийн дэлгэрэнгүй мэдээлэл байрлана.',
    'image': 'assets/img/shop1.jpg',
    'status': false,
  },
  {
    'id': 2,
    'name': 'Тест Дэлгүүр 2',
    'description': 'Тухайн дэлгүүрийн дэлгэрэнгүй мэдээлэл байрлана.',
    'image': 'assets/img/shop2.jpg',
    'status': false,
  }
];

List cartProducts = [
  {
    'id': 7,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_7.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Шинэ бараа',
    'status': 'Тийм',
    'count': '350',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': '42 67 98',
    'color': 'хар цагаан бор',
    'shop_id': 2,
    'qty': 1
  },
  {
    'id': 1,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_1.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Онцлох',
    'status': 'Тийм',
    'count': '350',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': '42 67 98',
    'color': 'хар цагаан бор',
    'shop_id': 1,
    'qty': 1
  },
  {
    'id': 3,
    'name': 'Nike SB Zoom Blazer Low Pro',
    'description': 'Энд тухайн барааны дэлгэрнгүй мэдээлэл байрлана.',
    'image': 'assets/img/product_3.png',
    'category': 'Clothes',
    'subcategory': 'Lifestyle',
    'type': 'Онцлох',
    'status': 'Тийм',
    'count': '650',
    'price': '850000',
    'b_shimtgel': '70000',
    's_shimtgel': '50000',
    'producer': '550000',
    'size': '42 67 98',
    'color': 'хар цагаан бор',
    'shop_id': 1,
  },
];
